// The nginx config for the proxy in front of 1Password Connect: it passes only GET and HEAD
// and returns 405 for any other method. Connect's own address is the pod's loopback. The
// Authorization header passes through unchanged, and the access log is nginx's combined
// format, which has no Authorization field: never log $http_authorization. The image's own
// nginx.conf already keeps the pid and the temp files under /tmp.
//
// The Connect token can write today, so the method rule is the read-only control until the
// token is reissued read-only.
export const onePasswordConnectProxyPort = 8000;

export function buildOnePasswordConnectProxyConfig(): string {
  return `${[
    '# generated by infra/build-onepassword-connect-proxy-config.ts',
    '',
    'server {',
    `  listen ${onePasswordConnectProxyPort};`,
    '  server_tokens off;',
    '  access_log /dev/stdout combined;',
    '',
    '  if ($request_method !~ ^(GET|HEAD)$) {',
    '    return 405;',
    '  }',
    '',
    '  location / {',
    '    proxy_pass http://127.0.0.1:8080;',
    '    proxy_set_header Host $host;',
    '  }',
    '}',
  ].join('\n')}\n`;
}
