// The nginx config for the proxy in front of 1Password Connect: it admits only the listed
// public IPv4 addresses, as Cloudflare reports them in Cf-Connecting-Ip, and only GET and
// HEAD. Connect's own address is the pod's loopback. The Authorization header passes
// through unchanged, and the access log is nginx's combined format, which has no
// Authorization field: never log $http_authorization. The image's own nginx.conf already
// keeps the pid and the temp files under /tmp.
export const onePasswordConnectProxyPort = 8000;

export function buildOnePasswordConnectProxyConfig(allowedSources: readonly string[]): string {
  if (allowedSources.length === 0) {
    throw new Error('the Connect proxy needs at least one allowed source address');
  }

  const entries = allowedSources.map((address) => `  ${assertIPv4(address)}/32 1;`);

  return `${[
    '# generated by infra/build-onepassword-connect-proxy-config.ts',
    '',
    'geo $http_cf_connecting_ip $connect_source_allowed {',
    '  default 0;',
    ...entries,
    '}',
    '',
    'server {',
    `  listen ${onePasswordConnectProxyPort};`,
    '  server_tokens off;',
    '  access_log /dev/stdout combined;',
    '',
    '  if ($connect_source_allowed = 0) {',
    '    return 403;',
    '  }',
    '',
    '  if ($request_method !~ ^(GET|HEAD)$) {',
    '    return 405;',
    '  }',
    '',
    '  location / {',
    '    proxy_pass http://127.0.0.1:8080;',
    '    proxy_set_header Host $host;',
    '  }',
    '}',
  ].join('\n')}\n`;
}

const ipv4Pattern =
  /^(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)$/u;

// the address goes into nginx syntax, so only a plain dotted quad passes
function assertIPv4(address: string): string {
  if (!ipv4Pattern.test(address)) {
    throw new Error('allowed source is not a plain IPv4 address');
  }

  return address;
}
