// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("onidel");

/**
 * Onidel API key. Falls back to the ONIDEL_API_KEY environment variable.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey") ?? utilities.getEnv("ONIDEL_API_KEY");
    },
    enumerable: true,
});

/**
 * API base URL. Defaults to https://api.cloud.onidel.com.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * Team ID to act in. When unset, the API's default team is used; SSH keys, which need an explicit team, use the caller's only team.
 */
export declare const teamId: string | undefined;
Object.defineProperty(exports, "teamId", {
    get() {
        return __config.get("teamId");
    },
    enumerable: true,
});

