// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An allow rule in an Onidel firewall group. Import with `<firewallId>/<ruleId>`.
 */
export class FirewallRule extends pulumi.CustomResource {
    /**
     * Get an existing FirewallRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): FirewallRule {
        return new FirewallRule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'onidel:index:FirewallRule';

    /**
     * Returns true if the given object is an instance of FirewallRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FirewallRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FirewallRule.__pulumiType;
    }

    declare public /*out*/ readonly action: pulumi.Output<string>;
    /**
     * Rule description (max 255 characters). Updatable in place.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * ID of the FirewallGroup the rule belongs to.
     */
    declare public readonly firewallId: pulumi.Output<string>;
    declare public /*out*/ readonly ipType: pulumi.Output<string>;
    /**
     * Port or range, e.g. `443` or `8000:9000`. Omit for ICMP.
     */
    declare public readonly port: pulumi.Output<string | undefined>;
    /**
     * `tcp`, `udp`, `icmp` or `ipv6-icmp`. The API stores ICMP on a v6 subnet as `ipv6-icmp`.
     */
    declare public readonly protocol: pulumi.Output<string>;
    declare public /*out*/ readonly ruleId: pulumi.Output<string>;
    /**
     * Source IP, a special value (`Cloudflare`, `Onidel`, `HetrixTools`, `CloudFront`, `UptimeRobot`) or an IP list reference `list:<id>`.
     */
    declare public readonly subnet: pulumi.Output<string>;
    /**
     * CIDR prefix length of the subnet, e.g. 0 with subnet `0.0.0.0` for anywhere.
     */
    declare public readonly subnetSize: pulumi.Output<number>;

    /**
     * Create a FirewallRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FirewallRuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.firewallId === undefined && !opts.urn) {
                throw new Error("Missing required property 'firewallId'");
            }
            if (args?.protocol === undefined && !opts.urn) {
                throw new Error("Missing required property 'protocol'");
            }
            if (args?.subnet === undefined && !opts.urn) {
                throw new Error("Missing required property 'subnet'");
            }
            if (args?.subnetSize === undefined && !opts.urn) {
                throw new Error("Missing required property 'subnetSize'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["firewallId"] = args?.firewallId;
            resourceInputs["port"] = args?.port;
            resourceInputs["protocol"] = args?.protocol;
            resourceInputs["subnet"] = args?.subnet;
            resourceInputs["subnetSize"] = args?.subnetSize;
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["ipType"] = undefined /*out*/;
            resourceInputs["ruleId"] = undefined /*out*/;
        } else {
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["firewallId"] = undefined /*out*/;
            resourceInputs["ipType"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["protocol"] = undefined /*out*/;
            resourceInputs["ruleId"] = undefined /*out*/;
            resourceInputs["subnet"] = undefined /*out*/;
            resourceInputs["subnetSize"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["firewallId", "port", "protocol", "subnet", "subnetSize"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(FirewallRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a FirewallRule resource.
 */
export interface FirewallRuleArgs {
    /**
     * Rule description (max 255 characters). Updatable in place.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * ID of the FirewallGroup the rule belongs to.
     */
    firewallId: pulumi.Input<string>;
    /**
     * Port or range, e.g. `443` or `8000:9000`. Omit for ICMP.
     */
    port?: pulumi.Input<string | undefined>;
    /**
     * `tcp`, `udp`, `icmp` or `ipv6-icmp`. The API stores ICMP on a v6 subnet as `ipv6-icmp`.
     */
    protocol: pulumi.Input<string>;
    /**
     * Source IP, a special value (`Cloudflare`, `Onidel`, `HetrixTools`, `CloudFront`, `UptimeRobot`) or an IP list reference `list:<id>`.
     */
    subnet: pulumi.Input<string>;
    /**
     * CIDR prefix length of the subnet, e.g. 0 with subnet `0.0.0.0` for anywhere.
     */
    subnetSize: pulumi.Input<number>;
}
