// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { FirewallGroupArgs } from "./firewallGroup";
export type FirewallGroup = import("./firewallGroup").FirewallGroup;
export const FirewallGroup: typeof import("./firewallGroup").FirewallGroup = null as any;
utilities.lazyLoad(exports, ["FirewallGroup"], () => require("./firewallGroup"));

export { FirewallRuleArgs } from "./firewallRule";
export type FirewallRule = import("./firewallRule").FirewallRule;
export const FirewallRule: typeof import("./firewallRule").FirewallRule = null as any;
utilities.lazyLoad(exports, ["FirewallRule"], () => require("./firewallRule"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RdnsArgs } from "./rdns";
export type Rdns = import("./rdns").Rdns;
export const Rdns: typeof import("./rdns").Rdns = null as any;
utilities.lazyLoad(exports, ["Rdns"], () => require("./rdns"));

export { SshKeyArgs } from "./sshKey";
export type SshKey = import("./sshKey").SshKey;
export const SshKey: typeof import("./sshKey").SshKey = null as any;
utilities.lazyLoad(exports, ["SshKey"], () => require("./sshKey"));

export { VmArgs } from "./vm";
export type Vm = import("./vm").Vm;
export const Vm: typeof import("./vm").Vm = null as any;
utilities.lazyLoad(exports, ["Vm"], () => require("./vm"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "onidel:index:FirewallGroup":
                return new FirewallGroup(name, <any>undefined, { urn })
            case "onidel:index:FirewallRule":
                return new FirewallRule(name, <any>undefined, { urn })
            case "onidel:index:Rdns":
                return new Rdns(name, <any>undefined, { urn })
            case "onidel:index:SshKey":
                return new SshKey(name, <any>undefined, { urn })
            case "onidel:index:Vm":
                return new Vm(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("onidel", "index", _module)
pulumi.runtime.registerResourcePackage("onidel", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:onidel") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
