// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'onidel';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Onidel API key. Falls back to the ONIDEL_API_KEY environment variable.
     */
    declare public readonly apiKey: pulumi.Output<string | undefined>;
    /**
     * API base URL. Defaults to https://api.cloud.onidel.com.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * Team ID to act in. When unset, the provider uses the API key's only team.
     */
    declare public readonly teamId: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiKey"] = (args?.apiKey ? pulumi.secret(args.apiKey) : undefined) ?? utilities.getEnv("ONIDEL_API_KEY");
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["teamId"] = args?.teamId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Onidel API key. Falls back to the ONIDEL_API_KEY environment variable.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * API base URL. Defaults to https://api.cloud.onidel.com.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * Team ID to act in. When unset, the provider uses the API key's only team.
     */
    teamId?: pulumi.Input<string | undefined>;
}
