// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An Onidel virtual machine. Import an existing one with its UUID: `pulumi import onidel:index:Vm <name> <vm-id>`.
 */
export class Vm extends pulumi.CustomResource {
    /**
     * Get an existing Vm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Vm {
        return new Vm(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'onidel:index:Vm';

    /**
     * Returns true if the given object is an instance of Vm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vm.__pulumiType;
    }

    declare public /*out*/ readonly bgpEnabled: pulumi.Output<boolean>;
    /**
     * vCPU count. Replaces the VM: the API has no resize.
     */
    declare public readonly cpu: pulumi.Output<number>;
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Allow outbound SSH (port 22). Replaces the VM.
     */
    declare public readonly disableSshBlocking: pulumi.Output<boolean | undefined>;
    /**
     * Root disk in GB. Replaces the VM.
     */
    declare public readonly disk: pulumi.Output<number>;
    /**
     * FirewallGroup to attach. Updatable in place; unset detaches.
     */
    declare public readonly firewallGroupId: pulumi.Output<string | undefined>;
    /**
     * Instance type UUID. Replaces the VM.
     */
    declare public readonly instanceType: pulumi.Output<string | undefined>;
    /**
     * Enable IPv6. Updatable in place; unset leaves it as the API has it.
     */
    declare public readonly ipv6: pulumi.Output<boolean | undefined>;
    /**
     * Custom or system ISO to boot from. Replaces the VM.
     */
    declare public readonly isoId: pulumi.Output<string | undefined>;
    /**
     * Location, e.g. `Melbourne`. Replaces the VM.
     */
    declare public readonly location: pulumi.Output<string>;
    declare public /*out*/ readonly mainIpv4: pulumi.Output<string>;
    declare public /*out*/ readonly mainIpv6: pulumi.Output<string>;
    /**
     * Hostname and display name. Updatable in place.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * OS template ID (see GET /os_templates). Provide one of os, snapshotId or isoId. Replaces the VM.
     */
    declare public readonly os: pulumi.Output<number | undefined>;
    /**
     * Billing cycle: hourly, monthly, quarterly, semiannually, annually, biennially or triennially. Replaces the VM.
     */
    declare public readonly paymentCycle: pulumi.Output<string | undefined>;
    /**
     * RAM in MB. Replaces the VM.
     */
    declare public readonly ram: pulumi.Output<number>;
    /**
     * Snapshot to deploy from. Replaces the VM.
     */
    declare public readonly snapshotId: pulumi.Output<string | undefined>;
    /**
     * SshKey IDs installed at provisioning. Replaces the VM.
     */
    declare public readonly sshKeys: pulumi.Output<string[] | undefined>;
    /**
     * Startup script run on first boot. Replaces the VM.
     */
    declare public readonly startupScriptId: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly status: pulumi.Output<string>;
    declare public /*out*/ readonly template: pulumi.Output<string>;
    /**
     * VPC IDs to attach at provisioning. Replaces the VM.
     */
    declare public readonly vpcs: pulumi.Output<string[] | undefined>;

    /**
     * Create a Vm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VmArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cpu === undefined && !opts.urn) {
                throw new Error("Missing required property 'cpu'");
            }
            if (args?.disk === undefined && !opts.urn) {
                throw new Error("Missing required property 'disk'");
            }
            if (args?.location === undefined && !opts.urn) {
                throw new Error("Missing required property 'location'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.ram === undefined && !opts.urn) {
                throw new Error("Missing required property 'ram'");
            }
            resourceInputs["cpu"] = args?.cpu;
            resourceInputs["disableSshBlocking"] = args?.disableSshBlocking;
            resourceInputs["disk"] = args?.disk;
            resourceInputs["firewallGroupId"] = args?.firewallGroupId;
            resourceInputs["instanceType"] = args?.instanceType;
            resourceInputs["ipv6"] = args?.ipv6;
            resourceInputs["isoId"] = args?.isoId;
            resourceInputs["location"] = args?.location;
            resourceInputs["name"] = args?.name;
            resourceInputs["os"] = args?.os;
            resourceInputs["paymentCycle"] = args?.paymentCycle;
            resourceInputs["ram"] = args?.ram;
            resourceInputs["snapshotId"] = args?.snapshotId;
            resourceInputs["sshKeys"] = args?.sshKeys;
            resourceInputs["startupScriptId"] = args?.startupScriptId;
            resourceInputs["vpcs"] = args?.vpcs;
            resourceInputs["bgpEnabled"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["mainIpv4"] = undefined /*out*/;
            resourceInputs["mainIpv6"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["template"] = undefined /*out*/;
        } else {
            resourceInputs["bgpEnabled"] = undefined /*out*/;
            resourceInputs["cpu"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["disableSshBlocking"] = undefined /*out*/;
            resourceInputs["disk"] = undefined /*out*/;
            resourceInputs["firewallGroupId"] = undefined /*out*/;
            resourceInputs["instanceType"] = undefined /*out*/;
            resourceInputs["ipv6"] = undefined /*out*/;
            resourceInputs["isoId"] = undefined /*out*/;
            resourceInputs["location"] = undefined /*out*/;
            resourceInputs["mainIpv4"] = undefined /*out*/;
            resourceInputs["mainIpv6"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["os"] = undefined /*out*/;
            resourceInputs["paymentCycle"] = undefined /*out*/;
            resourceInputs["ram"] = undefined /*out*/;
            resourceInputs["snapshotId"] = undefined /*out*/;
            resourceInputs["sshKeys"] = undefined /*out*/;
            resourceInputs["startupScriptId"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["template"] = undefined /*out*/;
            resourceInputs["vpcs"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["cpu", "disableSshBlocking", "disk", "instanceType", "isoId", "location", "os", "paymentCycle", "ram", "snapshotId", "sshKeys[*]", "startupScriptId", "vpcs[*]"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Vm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Vm resource.
 */
export interface VmArgs {
    /**
     * vCPU count. Replaces the VM: the API has no resize.
     */
    cpu: pulumi.Input<number>;
    /**
     * Allow outbound SSH (port 22). Replaces the VM.
     */
    disableSshBlocking?: pulumi.Input<boolean | undefined>;
    /**
     * Root disk in GB. Replaces the VM.
     */
    disk: pulumi.Input<number>;
    /**
     * FirewallGroup to attach. Updatable in place; unset detaches.
     */
    firewallGroupId?: pulumi.Input<string | undefined>;
    /**
     * Instance type UUID. Replaces the VM.
     */
    instanceType?: pulumi.Input<string | undefined>;
    /**
     * Enable IPv6. Updatable in place; unset leaves it as the API has it.
     */
    ipv6?: pulumi.Input<boolean | undefined>;
    /**
     * Custom or system ISO to boot from. Replaces the VM.
     */
    isoId?: pulumi.Input<string | undefined>;
    /**
     * Location, e.g. `Melbourne`. Replaces the VM.
     */
    location: pulumi.Input<string>;
    /**
     * Hostname and display name. Updatable in place.
     */
    name: pulumi.Input<string>;
    /**
     * OS template ID (see GET /os_templates). Provide one of os, snapshotId or isoId. Replaces the VM.
     */
    os?: pulumi.Input<number | undefined>;
    /**
     * Billing cycle: hourly, monthly, quarterly, semiannually, annually, biennially or triennially. Replaces the VM.
     */
    paymentCycle?: pulumi.Input<string | undefined>;
    /**
     * RAM in MB. Replaces the VM.
     */
    ram: pulumi.Input<number>;
    /**
     * Snapshot to deploy from. Replaces the VM.
     */
    snapshotId?: pulumi.Input<string | undefined>;
    /**
     * SshKey IDs installed at provisioning. Replaces the VM.
     */
    sshKeys?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Startup script run on first boot. Replaces the VM.
     */
    startupScriptId?: pulumi.Input<string | undefined>;
    /**
     * VPC IDs to attach at provisioning. Replaces the VM.
     */
    vpcs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
